### ISSUE TITLE
JWT creation tool is written in PHP

### ISSUE THREAD

**Issue by JoshuaPK** [docusign/code-examples-bash#6]
For the BASH script examples, can you consider providing a version of the JWT creation tool in Python instead of (or in addition to) PHP?  Many of us in regulated environments do not have access to servers with PHP installed nor do we have access to install PHP on our local machines.  Since Python is used as a systems language in most popular Linux distros it's far more likely to be installed and accessible than PHP is.  (I examined the Python examples and those will not work because we can't install Flask, and these sorts of utilities should not rely on being able to run local web servers.)

**Comment by LarryKlugerDS** [comment]
This is a good idea. We will file an enhancement ticket for the team to evaluate.

**Comment by LarryKlugerDS** [comment]
This is filed as enhancement request DEVDOCS-3552

**Comment by InbarGazit** [comment]
We support both Python and PHP now.
