### ISSUE TITLE
eSignature "Creating a brand" example broken

### ISSUE THREAD

**Issue by manuca** [docusign/code-examples-bash#8]
## Issue

When running the example using the launcher `bash launcher.sh` after obtaining the authentication token via the JWT method and trying to run example 28 of the eSignature API I get the following error:

```bash
: command not found/eg028CreatingABrand.sh: line 2: 
examples/eSignature/eg028CreatingABrand.sh: line 78: syntax error: unexpected end of file
```

## Screenshot
<img width="697" alt="Screen Shot 2021-09-23 at 10 32 34" src="https://user-images.githubusercontent.com/686709/134516667-545fbe09-75fe-41fb-9015-b39c7833c56e.png">

**Comment by InbarGazit** [comment]
Sorry, I just tried and cannot reproduce. Can you please try again with latest code? does it work with Auth Code Grant? do you have other examples working ok? may need to get more details to see the issue you see.
