### ISSUE TITLE
Create Template out of the box

### ISSUE THREAD

**Issue by vegasdevguy** [docusign/code-examples-bash#9]
Create template submit button out of the box, gives you an error "undefined local variable or method `template_name' for"

<b style="color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Did you mean?</b><span style="color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><ul style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="correction" style="list-style-type: none;">template_request</li></ul><div class="source " id="frame-source-0-0" style="border: 1px solid rgb(217, 217, 217); background: rgb(236, 236, 236); max-width: 978px; color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#162</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background-color: rgb(255, 255, 255);">

160 161 162 163 164 165 | template_request = DocuSign_eSign::EnvelopeTemplate.new(       'documents' => [document],       'name' => template_name,       'emailSubject' => 'Please sign this document',       'envelopeTemplateDefinition' => envelope_template_definition,       'recipients' => DocuSign_eSign::Recipients.new(
-- | --

</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p><div id="traces-0" style="color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="http://localhost:3000/eg008#" onclick="hide('Framework-Trace-0');hide('Full-Trace-0');show('Application-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Application Trace</a><span> </span>|<span> </span><a href="http://localhost:3000/eg008#" onclick="hide('Application-Trace-0');hide('Full-Trace-0');show('Framework-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Framework Trace</a><span> </span>|<span> </span><a href="http://localhost:3000/eg008#" onclick="hide('Application-Trace-0');hide('Framework-Trace-0');show('Full-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Full Trace</a><div id="Application-Trace-0" style="display: block;"><code class="traces" style="font-size: 11px;"><a class="trace-frames trace-frames-0" data-exception-object-id="37420" data-frame-id="0" href="http://localhost:3000/eg008#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">app/services/e_sign/eg008_create_template_service.rb:162:in `make_template_req'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="37420" data-frame-id="1" href="http://localhost:3000/eg008#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">app/services/e_sign/eg008_create_template_service.rb:26:in `worker'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="37420" data-frame-id="2" href="http://localhost:3000/eg008#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">app/controllers/e_sign/eg008_create_template_controller.rb:14:in `create'</a><br></code></div></div><h2 class="request-heading" style="color: rgb(204, 0, 0); line-height: 25px; margin-top: 30px; font-family: helvetica, verdana, arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Request</h2><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b>Parameters</b>:</p><pre style="font-size: 11px; white-space: pre-wrap; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">None</pre><div class="details" style="border: 1px solid rgb(208, 208, 208); border-radius: 4px; margin: 1em 0px; display: block; max-width: 978px; color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="summary" style="padding: 8px 15px; border-bottom: 1px solid rgb(208, 208, 208); display: block;"><a href="http://localhost:3000/eg008#" onclick="return toggleSessionDump()" style="color: rgb(152, 9, 5);">Toggle session dump</a></div></div><div class="details" style="border: 1px solid rgb(208, 208, 208); border-radius: 4px; margin: 1em 0px; display: block; max-width: 978px; color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="summary" style="padding: 8px 15px; border-bottom: 1px solid rgb(208, 208, 208); display: block;"><a href="http://localhost:3000/eg008#" onclick="return toggleEnvDump()" style="color: rgb(152, 9, 5);">Toggle env dump</a></div></div>Did you mean?
template_request
Extracted source (around line #162):
160
161
162
163
164
165
              
    template_request = DocuSign_eSign::EnvelopeTemplate.new(
      'documents' => [document],
      'name' => template_name,
      'emailSubject' => 'Please sign this document',
      'envelopeTemplateDefinition' => envelope_template_definition,
      'recipients' => DocuSign_eSign::Recipients.new(

[Application Trace](http://localhost:3000/eg008#) | [Framework Trace](http://localhost:3000/eg008#) | [Full Trace](http://localhost:3000/eg008#)
[app/services/e_sign/eg008_create_template_service.rb:162:in `make_template_req'](http://localhost:3000/eg008#)
[app/services/e_sign/eg008_create_template_service.rb:26:in `worker'](http://localhost:3000/eg008#)
[app/controllers/e_sign/eg008_create_template_controller.rb:14:in `create'](http://localhost:3000/eg008#)
Request
Parameters:

None
[Toggle session dump](http://localhost:3000/eg008#)
[Toggle env dump](http://localhost:3000/eg008#)

**Comment by InbarGazit** [comment]
Are you talking about Ruby or Bash code? this is the Bash repo, so I'm confused

**Comment by InbarGazit** [comment]
Please see update to Ruby code that fixed this issue here - https://github.com/docusign/code-examples-ruby/commit/490ffc9a500d7c0cce65c186f8b660c7e3c3112a
